<Project>
  <Import Project="$(MSBuildThisFileDirectory)SemanticVersion.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Documentation</Configurations>
    <NuGetAuditMode>all</NuGetAuditMode>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>$(SemanticVersion).0</AssemblyVersion>
    <FileVersion>$(SemanticVersion).0</FileVersion>
    <VersionPrefix>$(SemanticVersion)</VersionPrefix>
  </PropertyGroup>

  <PropertyGroup>

    <Product>Gorm</Product>
  </PropertyGroup>

  <ItemGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <PackageReference Include="MSTest" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <!-- Attempt to determine the solution directory -->
  <PropertyGroup>
    <!-- Ensure the SolutionDir has a trailing backslash -->
    <SolutionDir Condition="'$(SolutionDir)' == '' OR !HasTrailingSlash('$(SolutionDir)')">$(MSBuildThisFileDirectory)\</SolutionDir>
  </PropertyGroup>

  <ItemGroup Condition="'$(MSBuildProjectName)' != 'SolutionItems'">

  </ItemGroup>

  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Tests'))">
    <RunSettingsFilePath>$(SolutionDir)normal-test-projects.runsettings</RunSettingsFilePath>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Specs'))">
    <RunSettingsFilePath>$(SolutionDir)scenario-test-projects.runsettings</RunSettingsFilePath>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
</Project>