using Gorm.Application.Context;
using Gorm.Application.Diagnostics;
using Gorm.Application.Execution;
using Gorm.Application.Execution.InMemory;
using Gorm.Application.Querying;
using Gorm.Core.Configuration;
using Gorm.Core.Primitives;

var context = new FirstGraphContext().UseInMemory();
var person = new PersonNode { Id = Guid.NewGuid(), Name = "Alice" };
var project = new ProjectNode { Id = Guid.NewGuid(), Code = "GORM" };

context.Add(person);
context.Add(project);
context.Connect<WorksOnEdge, PersonNode, ProjectNode>(person, project);
await context.SaveChangesAsync();

var query = context.Set<PersonNode>()
    .Where(x => x.Id == person.Id)
    .Outgoing<WorksOnEdge, ProjectNode>();

var projects = await query.ToListAsync();
if (projects.Count != 1 || projects[0].Code != "GORM")
{
    throw new InvalidOperationException("The first graph traversal did not return the expected project.");
}

Console.WriteLine($"{person.Name} works on {projects[0].Code}.");

var explanation = query.Explain();
if (string.IsNullOrWhiteSpace(explanation.Sql) || !explanation.Sql.Contains("MATCH", StringComparison.OrdinalIgnoreCase))
{
    throw new InvalidOperationException("Expected real SQL Server Graph translation from GORM.");
}

Console.WriteLine("SQL generated by GORM (not executed against SQL Server in this sample):");
Console.WriteLine(explanation.Sql);
Console.WriteLine("GORM getting-started sample passed.");

internal sealed class FirstGraphContext : GraphContext
{
    protected override void OnModelCreating(GraphModelBuilder modelBuilder)
    {
        modelBuilder.Node<PersonNode>(node =>
        {
            node.ToTable("Persons");
            node.Property(x => x.Name);
            node.HasOutgoingRelationship<WorksOnEdge, ProjectNode>(nameof(PersonNode.Projects));
            node.HasNavigation(x => x.Projects, nameof(PersonNode.Projects));
        });

        modelBuilder.Node<ProjectNode>(node =>
        {
            node.ToTable("Projects");
            node.Property(x => x.Code);
            node.HasIncomingRelationship<WorksOnEdge, PersonNode>("Contributors");
        });

        modelBuilder.Edge<WorksOnEdge>(edge =>
        {
            edge.ToTable("WorksOn");
            edge.From<PersonNode>();
            edge.To<ProjectNode>();
        });
    }
}

internal sealed class PersonNode : Node
{
    public string Name { get; set; } = string.Empty;

    public List<ProjectNode> Projects { get; set; } = [];
}

internal sealed class ProjectNode : Node
{
    public string Code { get; set; } = string.Empty;
}

internal sealed class WorksOnEdge : Edge
{
}
